# fly.toml

app = "culinary-backend"
primary_region = "jnb"

[build]

[env]
PORT = "5000"
MONGODB_URI = "mongodb+srv://Olajumoke_dbUser02:Holowoh01@cluster0.qnj4zrh.mongodb.net/culinaryDB?retryWrites=true&w=majority"
JWT_SECRET = "secretstrongpass"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
